FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ./Gateway/*.csproj ./Gateway/
RUN dotnet restore ./Gateway/Gateway.csproj

COPY ./Gateway/. ./Gateway/
WORKDIR /app/Gateway
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out ./

EXPOSE 7777

ENTRYPOINT ["dotnet", "Gateway.dll"]
