version: '3.3'

services:
  gateway:
    container_name: ocelot-gateway
    build:      
      context: .
      dockerfile: ./src/Gateway/Dockerfile
    ports:
      - "7777:80"
    networks:
      - evaluation-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sales-api
  sales-api:
    container_name: sales-api
    build:      
      context: .
      dockerfile: ./src/SalesApi/Dockerfile
    ports:
      - "8081:80"
    networks:
      - evaluation-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-server;Database=SalesDb;User=root;Password=rootpassword;
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=user
      - RabbitMq__Password=password
      - RabbitMq__Port=5672
    depends_on:
      - mysql-server
      - rabbitmq   
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SalesDb
    ports:
      - "3307:3306"
    networks:
      - evaluation-network
    volumes:
      - mysql_data:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq
    hostname: hostname
    image: rabbitmq:3-management
    networks:
    - evaluation-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

networks:
  evaluation-network:
    external: true

volumes:
  mysql_data:
