FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/SalesApi/SalesApi.csproj ./SalesApi/
COPY src/Sales.Domain/Sales.Domain.csproj ./Sales.Domain/
COPY src/Sales.Application/Sales.Application.csproj ./Sales.Application/
COPY src/Sales.Infrastructure/Sales.Infrastructure.csproj ./Sales.Infrastructure/

RUN dotnet restore ./SalesApi/SalesApi.csproj

COPY src/ .

RUN dotnet publish ./SalesApi/SalesApi.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "SalesApi.dll"]